In [1]:
import pandas as pd
df = pd.read_csv("Youtube01-Psy.csv")

In [2]:
df.head()

COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   

   CLASS  
0      1  
1      1  
2      1  
3      1  
4      1

In [3]:
len(df.query('CLASS == 1'))

175

In [4]:
len(df.query('CLASS == 0'))

175

In [5]:
len(df)

350

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [7]:
dvec = vectorizer.fit_transform(df['CONTENT'])

In [8]:
dvec

<350x1418 sparse matrix of type '<class 'numpy.int64'>'
	with 4354 stored elements in Compressed Sparse Row format>

In [9]:
analyze = vectorizer.build_analyzer()

In [10]:
print(df['CONTENT'][349])
analyze(df['CONTENT'][349])

The first billion viewed this because they thought it was really cool, the  other billion and a half came to see how stupid the first billion were...


['the',
 'first',
 'billion',
 'viewed',
 'this',
 'because',
 'they',
 'thought',
 'it',
 'was',
 'really',
 'cool',
 'the',
 'other',
 'billion',
 'and',
 'half',
 'came',
 'to',
 'see',
 'how',
 'stupid',
 'the',
 'first',
 'billion',
 'were']

In [11]:
vectorizer.get_feature_names()

D:\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['00',
 '000',
 '02',
 '034',
 '05',
 '08',
 '10',
 '100',
 '100000415527985',
 '10200253113705769',
 '1030',
 '1073741828',
 '11',
 '1111',
 '112720997191206369631',
 '12',
 '123',
 '124',
 '124923004',
 '126',
 '127',
 '13017194',
 '131338190916',
 '1340488',
 '1340489',
 '1340490',
 '1340491',
 '1340492',
 '1340493',
 '1340494',
 '1340499',
 '1340500',
 '1340502',
 '1340503',
 '1340504',
 '1340517',
 '1340518',
 '1340519',
 '1340520',
 '1340521',
 '1340522',
 '1340523',
 '1340524',
 '134470083389909',
 '1415297812',
 '1495323920744243',
 '1496241863981208',
 '1496273723978022',
 '1498561870415874',
 '161620527267482',
 '171183229277',
 '19',
 '19924',
 '1firo',
 '1m',
 '20',
 '2009',
 '2012',
 '2012bitches',
 '2013',
 '2014',
 '201470069872822',
 '2015',
 '2017',
 '210',
 '23',
 '24',
 '24398',
 '243a',
 '279',
 '29',
 '2b',
 '2billion',
 '2x10',
 '300',
 '3000',
 '313327',
 '315',
 '322',
 '33',
 '33gxrf',
 '39',
 '390875584405933',
 '391725794320912',
 '40beuutvu2zkxk4utgpz8k',
 '

In [12]:
dshuf = df.sample(frac=1)

In [13]:
df_train = dshuf[:300]
df_test = dshuf[300:]
df_train_att = vectorizer.fit_transform(df_train['CONTENT'])  #fir bag-of-words on training set
df_test_att = vectorizer.transform(df_test['CONTENT'])
df_train_label = df_train['CLASS']
df_test_label = df_test['CLASS']

In [14]:
df_train_att

<300x1303 sparse matrix of type '<class 'numpy.int64'>'
	with 3783 stored elements in Compressed Sparse Row format>

In [15]:
df_test_att

<50x1303 sparse matrix of type '<class 'numpy.int64'>'
	with 454 stored elements in Compressed Sparse Row format>

In [16]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=80)

In [17]:
clf.fit(df_train_att, df_train_label)

RandomForestClassifier(n_estimators=80)

In [18]:
clf.score(df_test_att, df_test_label)

0.94

In [19]:
from sklearn.metrics import confusion_matrix
pred_labels = clf.predict(df_test_att)
confusion_matrix(df_test_label, pred_labels)

array([[32,  0],
       [ 3, 15]], dtype=int64)

In [20]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, df_train_att, df_train_label, cv=5)

# show average score and +/- two standard deviations away (covering 95% of scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.97 (+/- 0.04)


In [21]:
# load all datasets and combine them
d = pd.concat([pd.read_csv("Youtube02-KatyPerry.csv"),
               pd.read_csv("Youtube03-LMFAO.csv"),
               pd.read_csv("Youtube04-Eminem.csv"),
               pd.read_csv("Youtube05-Shakira.csv")])

In [22]:
len(d)

1606

In [23]:
len(d.query("CLASS == 1"))

830

In [24]:
len(d.query("CLASS == 0"))

776

In [25]:
dshuf = d.sample(frac=1)
d_content = dshuf['CONTENT']
d_label = dshuf['CLASS']

In [26]:
# set a pipeline
from sklearn.pipeline import Pipeline, make_pipeline
pipeline = Pipeline([('bag-of-words',CountVectorizer()),
                    ('random-forest', RandomForestClassifier()),])
pipeline

Pipeline(steps=[('bag-of-words', CountVectorizer()),
                ('random-forest', RandomForestClassifier())])

In [27]:
make_pipeline(CountVectorizer(), RandomForestClassifier())

Pipeline(steps=[('countvectorizer', CountVectorizer()),
                ('randomforestclassifier', RandomForestClassifier())])

In [28]:
pipeline.fit(d_content[:1500],d_label[:1500])

Pipeline(steps=[('bag-of-words', CountVectorizer()),
                ('random-forest', RandomForestClassifier())])

In [29]:
pipeline.score(d_content[1500:],d_label[1500:])

0.9716981132075472

In [30]:
pipeline.predict(["What a neat video!"])

array([0], dtype=int64)

In [31]:
pipeline.predict(["plz subscribe to my channel"])

array([1], dtype=int64)

In [32]:
scores = cross_val_score(pipeline, d_content, d_label, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.96 (+/- 0.04)


In [49]:
# add tfidf
from sklearn.feature_extraction.text import TfidfTransformer
pipeline2 = make_pipeline(CountVectorizer(),
                         TfidfTransformer(norm=None),
                         RandomForestClassifier())
sorted(pipeline.get_params().keys())

['bag-of-words',
 'bag-of-words__analyzer',
 'bag-of-words__binary',
 'bag-of-words__decode_error',
 'bag-of-words__dtype',
 'bag-of-words__encoding',
 'bag-of-words__input',
 'bag-of-words__lowercase',
 'bag-of-words__max_df',
 'bag-of-words__max_features',
 'bag-of-words__min_df',
 'bag-of-words__ngram_range',
 'bag-of-words__preprocessor',
 'bag-of-words__stop_words',
 'bag-of-words__strip_accents',
 'bag-of-words__token_pattern',
 'bag-of-words__tokenizer',
 'bag-of-words__vocabulary',
 'memory',
 'random-forest',
 'random-forest__bootstrap',
 'random-forest__ccp_alpha',
 'random-forest__class_weight',
 'random-forest__criterion',
 'random-forest__max_depth',
 'random-forest__max_features',
 'random-forest__max_leaf_nodes',
 'random-forest__max_samples',
 'random-forest__min_impurity_decrease',
 'random-forest__min_samples_leaf',
 'random-forest__min_samples_split',
 'random-forest__min_weight_fraction_leaf',
 'random-forest__n_estimators',
 'random-forest__n_jobs',
 'random-forest

In [50]:
scores = cross_val_score(pipeline2, d_content, d_label, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.96 (+/- 0.03)


In [51]:
pipeline2.steps

[('countvectorizer', CountVectorizer()),
 ('tfidftransformer', TfidfTransformer(norm=None)),
 ('randomforestclassifier', RandomForestClassifier())]

In [54]:
#parameter search
parameters = {
    'countvectorizer__max_features': (None, 1000, 2000),
    'countvectorizer__ngram_range': ((1,1), (1,2)),
    'countvectorizer__stop_words': ('english', None),
    'tfidftransformer__use_idf': (True, False),
    'randomforestclassifier__n_estimators': (20, 50, 100)
}

from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(pipeline2, parameters, n_jobs=-1, verbose=1, cv=5)

In [55]:
grid_search.fit(d_content, d_label)

Fitting 5 folds for each of 72 candidates, totalling 360 fits


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('countvectorizer', CountVectorizer()),
                                       ('tfidftransformer',
                                        TfidfTransformer(norm=None)),
                                       ('randomforestclassifier',
                                        RandomForestClassifier())]),
             n_jobs=-1,
             param_grid={'countvectorizer__max_features': (None, 1000, 2000),
                         'countvectorizer__ngram_range': ((1, 1), (1, 2)),
                         'countvectorizer__stop_words': ('english', None),
                         'randomforestclassifier__n_estimators': (20, 50, 100),
                         'tfidftransformer__use_idf': (True, False)},
             verbose=1)

In [58]:
print("Best score: %0.3f" % grid_search.best_score_)
print("Best parameters set: ")
best_parameters = grid_search.best_estimator_.get_params()
for param_name in sorted(parameters.keys()):
    print("\t%s: %r" % (param_name, best_parameters[param_name]))

Best score: 0.960
Best parameters set: 
	countvectorizer__max_features: 1000
	countvectorizer__ngram_range: (1, 1)
	countvectorizer__stop_words: 'english'
	randomforestclassifier__n_estimators: 100
	tfidftransformer__use_idf: True
